package main

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/example/kestrel/internal/config"
	"github.com/example/kestrel/internal/execlog"
	"github.com/example/kestrel/internal/guard"
	"github.com/example/kestrel/internal/logging"
	"github.com/example/kestrel/internal/runner"
	"github.com/spf13/cobra"
)

var (
	environment    string
	verbose        bool
	cfg            *config.Config
	logCleanup     func()
	execlogCleanup func()
)

var rootCmd = &cobra.Command{
	Use:   "kestci",
	Short: "Kestrel CI — deterministic helm & terraform orchestration for CI/CD",
	Long: `A non-interactive CLI for CI/CD pipelines that reads .kestconfig and
executes helm and terraform commands. AWS credentials come from the
environment (OIDC, env vars). Kubeconfig is set up automatically from
target cluster and region fields.`,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		cleanup, err := logging.Init()
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not initialize logging: %v\n", err)
		} else {
			logCleanup = cleanup
		}

		elCleanup, err := execlog.Init()
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not initialize exec log: %v\n", err)
		} else {
			execlogCleanup = elCleanup
		}

		cfg, err = config.Load()
		if err != nil {
			return err
		}

		slog.Debug("config loaded", "chart", cfg.Helm.Chart, "iac_dir", cfg.Terraform.IACDir)
		if verbose {
			fmt.Fprintf(os.Stderr, "debug: config loaded (chart=%s, iac_dir=%s)\n",
				cfg.Helm.Chart, cfg.Terraform.IACDir)
		}

		slog.Info("kestci invoked",
			"command", cmd.CommandPath(),
			"args", args,
			"environment", environment,
			"ci", guard.IsCI(),
		)

		return nil
	},
	PersistentPostRun: func(cmd *cobra.Command, args []string) {
		if execlogCleanup != nil {
			execlogCleanup()
		}
		if logCleanup != nil {
			logCleanup()
		}
	},
}

// resolveTargetForCI resolves a target and sets up kubeconfig from the
// target's cluster + region fields. AWS credentials are expected to already
// be in the environment (via OIDC or env vars).
//
// Returns a ResolvedTarget with KubeContext set to the EKS ARN-format
// context generated by `aws eks update-kubeconfig`. AwsProfile is left
// empty — CI uses ambient credentials.
func resolveTargetForCI(targetName string) (config.ResolvedTarget, error) {
	target, ok := cfg.Targets[targetName]
	if !ok {
		return config.ResolvedTarget{}, fmt.Errorf("target %q not configured (check your .kestconfig targets)", targetName)
	}

	resolved := config.ResolvedTarget{
		Cluster:   target.Cluster,
		Region:    target.Region,
		AccountID: target.AWSAccount,
	}

	// Set up kubeconfig if we have a cluster.
	if target.Cluster != "" && target.Region != "" {
		slog.Info("updating kubeconfig", "cluster", target.Cluster, "region", target.Region)
		if verbose {
			fmt.Fprintf(os.Stderr, "debug: updating kubeconfig for cluster %s in %s\n", target.Cluster, target.Region)
		}
		if err := runner.Run("aws", "eks", "update-kubeconfig",
			"--name", target.Cluster,
			"--region", target.Region,
		); err != nil {
			return config.ResolvedTarget{}, fmt.Errorf("failed to update kubeconfig for cluster %q: %w", target.Cluster, err)
		}

		// The generated context is the EKS ARN.
		if target.AWSAccount != "" {
			resolved.KubeContext = fmt.Sprintf(
				"arn:aws:eks:%s:%s:cluster/%s",
				target.Region, target.AWSAccount, target.Cluster,
			)
		}
	} else if target.Cluster != "" {
		return config.ResolvedTarget{}, fmt.Errorf(
			"target %q has cluster %q but no region — kestci needs both to set up kubeconfig",
			targetName, target.Cluster)
	}

	return resolved, nil
}

// requireCI returns an error if not running in a CI environment.
// kestci is meant for CI only — use kest for local development.
func requireCI() error {
	if !guard.IsCI() {
		return fmt.Errorf("kestci is designed for CI/CD pipelines; use 'kest' for local development\n" +
			"  Set CI=true to override (e.g. for local testing of CI workflows)")
	}
	return nil
}

// SetBuildInfo wires build-time version/commit/date into the root command,
// surfaced via `kestci --version`. Stamped by hanko via ldflags at build time.
func SetBuildInfo(version, commit, date string) {
	rootCmd.Version = fmt.Sprintf("%s (commit %s, built %s)", version, commit, date)
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func init() {
	rootCmd.PersistentFlags().StringVarP(&environment, "environment", "e", "", "target environment (required)")
	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "enable verbose/debug output")
}
